name: diyigemt             # nukkit运行时识别的插件名
main: net.diyigemt.mcpeplugin.MainPlugin  # 主类名称,不能以cn.nukkit开头
api: ["1.0.9"]
version: "1.0.0"              # 版本号
author: diyigemt  # 感谢qq1586235767的提议，作者名称不能使用纯数字，否则会发生类型转换异常，您可以使用字符串避免这个问题
description: diyigemt teleport plugin  # 介绍
#commands:
#  tpa:
#    usage: "/tpa aaa 请求传送到玩家aaa处"
#    description: "经典传送请求命令"
#    permission: diyigemtPlugin.tpa
#  back:
#    usage: "/back 返回到上一次传送的位置"
#    description: "经典传送命令"
#    permission: diyigemtPlugin.back
#  sethome:
#    usage: "/sethome 设置名称为home的家"
#    description: "设置一个家"
#    permission: diyigemtPlugin.sethome
#  home:
#    usage: "/home 返回到默认的家"
#    description: "经典传送命令"
#    permission: diyigemtPlugin.home
#  removehome:
#    usage: "/removehome home 删除默认的家"
#    description: "删除一个家"
#    permission: diyigemtPlugin.removehome
#permissions:
#  diyigemtPlugin.tpa:
#    description: "所有"
#    default: true
#  diyigemtPlugin.back:
#    description: "所有"
#    default: true
#  diyigemtPlugin.sethome:
#    description: "所有"
#    default: true
#  diyigemtPlugin.home:
#    description: "所有"
#    default: true
#  diyigemtPlugin.removehome:
#    description: "所有"
#    default: true